package org.intellij.plugin.zeppelin.idea.settings.interpreter;

import com.intellij.ui.ToolbarDecorator;
import com.intellij.ui.components.JBList;
import com.intellij.ui.table.TableView;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.intellij.plugin.zeppelin.constants.ZeppelinConstants;
import org.intellij.plugin.zeppelin.idea.common.AddStringValueButton;
import org.intellij.plugin.zeppelin.models.InterpreterOption;
import org.intellij.plugin.zeppelin.models.InterpreterProperty;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.CopyOnWriteArrayList;

import static com.intellij.ui.components.JBList.createDefaultListModel;

public class InterpreterSettingsForm extends JDialog {
    final static private String GLOBALLY = "Globally";
    final static private String CUSTOM = "Custom";


    private JPanel contentPane;

    private CopyOnWriteArrayList<String> dependenciesModelList;
    private JBList<String> dependenciesList;
    @SuppressWarnings("unused")
    private JPanel dependenciesPanel;

    private JComboBox<String> instantiationBox;
    private JComboBox<String> perNoteBox;
    private JComboBox<String> perUserBox;
    private JPanel customInstantiationPanel;
    @SuppressWarnings("unused")
    private JPanel propertiesPanel;
    private InterpreterPropertiesTableModel parametersModel = new InterpreterPropertiesTableModel();


    public InterpreterSettingsForm() {
        $$$setupUI$$$();
        setContentPane(contentPane);
        setModal(true);
    }

    @Override
    public JPanel getContentPane() {
        return contentPane;
    }

    public List<String> getDependenciesModelList() {
        return dependenciesModelList;
    }

    public String getPerNoteValue() {
        return (String) perNoteBox.getSelectedItem();
    }

    public String getPerUserValue() {
        return (String) perUserBox.getSelectedItem();
    }

    public void initDependenciesList(List<String> list) {
        dependenciesModelList = new CopyOnWriteArrayList<>(list);
        updateDependenciesList();
    }

    public void initPropertiesList(List<InterpreterProperty> list) {
        parametersModel.setItems(list);
    }

    public void initInstantiationTypes(List<String> values, InterpreterOption option) {
        ArrayList<String> instantiationValues = new ArrayList<>();
        instantiationValues.add(GLOBALLY);
        instantiationValues.add(CUSTOM);

        initComboBox(instantiationBox, instantiationValues, option.isGlobally() ? GLOBALLY : CUSTOM);
        customInstantiationPanel.setVisible(!option.isGlobally());
        instantiationBox.addItemListener(event -> {
            if (event.getStateChange() == ItemEvent.SELECTED) {
                boolean isGlobal = event.getItem().equals(GLOBALLY);
                customInstantiationPanel.setVisible(!isGlobal);
            }
        });

        initComboBox(perUserBox, values, option.getPerUser().toString());
        initComboBox(perNoteBox, values, option.getPerUser().toString());
    }

    public boolean isGlobally() {
        return Objects.equals(instantiationBox.getSelectedItem(), GLOBALLY);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(6, 5, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.add(dependenciesPanel, new GridConstraints(4, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Interpreter dependencies:");
        contentPane.add(label1, new GridConstraints(2, 0, 2, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Instantiation:");
        contentPane.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        instantiationBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Globally");
        defaultComboBoxModel1.addElement("Per note (scoped)");
        defaultComboBoxModel1.addElement("Per note (isolated)");
        instantiationBox.setModel(defaultComboBoxModel1);
        contentPane.add(instantiationBox, new GridConstraints(0, 1, 1, 4, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        customInstantiationPanel = new JPanel();
        customInstantiationPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(customInstantiationPanel, new GridConstraints(1, 1, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Per Note:");
        customInstantiationPanel.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        perNoteBox = new JComboBox();
        customInstantiationPanel.add(perNoteBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Per User:");
        customInstantiationPanel.add(label4, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        perUserBox = new JComboBox();
        customInstantiationPanel.add(perUserBox, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    private void createUIComponents() {
        createDependenciesPanel();
        createPropertiesPanel();
    }

    private void createDependenciesPanel() {
        dependenciesList = new JBList<>();
        dependenciesList.setEmptyText("There aren't dependencies");

        dependenciesPanel = ToolbarDecorator.createDecorator(dependenciesList)
                .setAddAction(anActionButton -> {
                    String newValue = new AddStringValueButton(
                            contentPane,
                            ZeppelinConstants.ADD_DEPENDENCY_TITLE,
                            ZeppelinConstants.DEPENDENCY_NAME_LABEL
                    ).getValue();
                    dependenciesModelList.add(newValue);
                    updateDependenciesList();
                }).setRemoveAction(anActionButton -> {
                    int selectedIndex = dependenciesList.getSelectedIndex();
                    dependenciesModelList.remove(selectedIndex);
                    updateDependenciesList();
                }).setEditAction(anActionButton -> {
                    int selectedItemId = dependenciesList.getSelectedIndex();
                    String oldValue = dependenciesModelList.get(selectedItemId);

                    String newValue = new AddStringValueButton(
                            contentPane,
                            ZeppelinConstants.EDIT_DEPENDENCY_TITLE,
                            ZeppelinConstants.DEPENDENCY_NAME_LABEL,
                            oldValue
                    ).getValue();

                    if (newValue == null) return;
                    dependenciesModelList.set(selectedItemId, newValue);
                    updateDependenciesList();
                })
                .createPanel();
    }

    private void createPropertiesPanel() {
        TableView<InterpreterProperty> myTable = new TableView<>();
        myTable.setModelAndUpdateColumns(parametersModel);
        propertiesPanel = ToolbarDecorator.createDecorator(myTable).createPanel();
        dependenciesList.setEmptyText("There aren't properties");

    }

    private void initComboBox(JComboBox<String> comboBox, List<String> values, String defaultValue) {
        String[] array = values.toArray(new String[0]);
        final DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(array);
        model.setSelectedItem(defaultValue);
        comboBox.setModel(model);
    }

    private void updateDependenciesList() {
        String[] array = dependenciesModelList.toArray(new String[0]);
        final DefaultListModel<String> model = createDefaultListModel(array);
        dependenciesList.setModel(model);
    }
}